
URL?=https://www.onlinetexteditor.com/
URL?=https://nrm.wikipedia.org/wiki/Rome



start :
	web-ext run --devtools   --start-url $(URL)

# https://extensionworkshop.com/documentation/develop/getting-started-with-web-ext/
install :
	npm install --global web-ext
