

start :
	web-ext run --devtools   --start-url https://nrm.wikipedia.org/wiki/Rome

# https://extensionworkshop.com/documentation/develop/getting-started-with-web-ext/
install :
	npm install --global web-ext
