

start :
	web-ext run  --bc --start-url https://www.onlinetexteditor.com/ --devtools

# https://extensionworkshop.com/documentation/develop/getting-started-with-web-ext/
install :
	npm install --global web-ext
